[versions]
komok = "1.0.13"
kotlin = "2.3.0-Beta2"
kotlinx-serialization = "1.9.0"
kotlinx-coroutines = "1.10.2"
logback = "1.5.20"
junit = "6.0.0"
aws-sdk = "1.5.69"

[libraries]
komok-tech-logging = { module = "io.heapy.komok:komok-tech-logging", version.ref = "komok"  }
komok-tech-to-be-injected = { module = "io.heapy.komok:komok-tech-to-be-injected", version.ref = "komok"  }
komok-tech-config-dotenv = { module = "io.heapy.komok:komok-tech-config-dotenv", version.ref = "komok"  }

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback"}

aws-sdk-ses = { module = "aws.sdk.kotlin:ses", version.ref = "aws-sdk" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
